apiVersion: v1
kind: Service
metadata:
  name: k8s-prometheus-adapter
  namespace: n9e
  labels:
    component: k8s-prometheus-adapter
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 32030
  selector:
    component: k8s-prometheus-adapter